### ISSUE TITLE
Backend not completed Yet

### ISSUE THREAD

**Issue by Gokul-Js** [Gokul-Js/MyAcademy#3]
Redux, MongoDB & Razor payment integration all are Pending to Execute

**Comment by Gokul-Js** [comment]
Duplicate of #2

**Comment by Gokul-Js** [comment]
Duplicate of #3

**Comment by Gokul-Js** [comment]
@riteshbenjwal please Review the backend of App once again & start implementing

**Comment by riteshbenjwal** [comment]
@Gokul-Js will start from tomorrow.

**Comment by riteshbenjwal** [comment]
Docker image for backend, frontend, nginx as a proxy, docker compose setup and admin panel related api's completed. Proceed with the frontend integration.
